[info]
# Bot版本，一般不需要修改
version = ["", "", ""]

[log]
# 0: DEBUG, 1: INFO, 2: SUCCESS, 3: WARNING
# 4: FAIL, 5: ERROR, 6: CRITICAL
log_level = "INFO"

[nonebot]
# 根据onebot服务端（如Lagrange）的配置来设置
listen_host = "127.0.0.1"
listen_port = 8080
token = ""

[group]
dev = 0
special = 0

[nsfw]
allowed_accounts = []

[diving_fish]
token = ""
